# Importing the librares

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import csv

# Importing the Dataset

In [12]:
#dataset = pd.read_csv('X_trainData_1.csv')
#labels=pd.read_csv('Y_trainData_1.csv')
dataset = pd.read_csv('SMOTE_updated_X_trainData_column_modified_CAP.csv')
#datalabels=pd.read_csv('X_trainData_column_modified_CAP.csv')


#X_train=dataset.iloc[:,:].values

X_train=dataset.iloc[:,:-1].values
#y_train=datalabels.iloc[:,-1].values
y_train=dataset.iloc[:,-1].values

In [13]:
print(X_train)


[[0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]]


In [14]:
print(y_train)

count1=0
count0=0

for n in y_train:
  if n==1:
    count1=count1+1
  else:
    count0=count0+1

print(count1)
print(count0)

[1 1 0 ... 0 0 0]
752
752


# Building the Logistic Reggression Model

In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

#from xgboost import XGBClassifier
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)

#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
#classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

#Predicting Validation set results 

In [16]:
#test_data = pd.read_csv('X_testData_column_modified_PCA_CAP.csv')
test_data = pd.read_csv('X_testData_1_modified.csv')

X_test=test_data.iloc[:,:].values


print(type(X_test))
print(len(X_test))
print(len(X_test[0]))
print(X_test)

<class 'numpy.ndarray'>
1000
219
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
y_pred = classifier.predict_proba(X_test)
#y_pred = classifier.predict(X_test)
#y_pred = ann.predict(X_test)
print(y_pred)

print(type(y_pred))
#y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_validation.reshape(len(y_validation),1)),1))

[[0.0017015  0.9982985 ]
 [0.01951036 0.98048964]
 [0.00848172 0.99151828]
 ...
 [0.00386378 0.99613622]
 [0.01283814 0.98716186]
 [0.0026747  0.9973253 ]]
<class 'numpy.ndarray'>


In [18]:
print(len(y_pred))


1000


In [19]:
submission_data = pd.read_csv('Y_testData_1_nolabels_CAP.csv')

ids=submission_data.iloc[:,:1].values
result=list()
k=0
#print(ids)
#print(y_pred[0])
#for i in ids:
  #result.append([ i[0], y_pred[i[0]-1][0] ])
  #result.append([ i[0], y_pred[i[0]-1][0] ])
  #result.append([ i[0], y_pred[k][0] ])
#  result.append([ i[0], y_pred[k][1] ])
#  k=k+1
  #print(y_pred[i[0]-1][0])
  #print('.')

for i in ids:
  result.append([ i[0], y_pred[i[0]-1][1] ])

result.insert(0, ['ID','CAP'])
print(result)

[['ID', 'CAP'], [1, 0.9982984973639061], [2, 0.980489644734137], [3, 0.9915182793178222], [4, 0.9900002584036697], [5, 0.9931480997825747], [6, 0.9915182793178222], [7, 0.9864860299881747], [8, 0.9809275676201809], [9, 0.9846479569548678], [10, 0.9880259273950711], [11, 0.9863766226671732], [12, 0.9930554838428494], [13, 0.9943043492381303], [14, 0.9509399549754135], [15, 0.9834852035819953], [16, 0.9764139378661495], [17, 0.9974737606076296], [18, 0.9810957193830697], [19, 0.9971702380097687], [20, 0.9842581204840752], [21, 0.9809572828700714], [22, 0.9900002584036697], [23, 0.9964255575437541], [24, 0.9957613082879178], [25, 0.9885923473105336], [26, 0.9980667013693], [27, 0.989285735556841], [28, 0.9915548370723604], [29, 0.9634651268331432], [30, 0.9866133716495956], [31, 0.9948233013273262], [32, 0.8292258409761419], [33, 0.9762835734041979], [34, 0.9895097158363712], [35, 0.6160071876906212], [36, 0.9869169622853114], [37, 0.9864860299881747], [38, 0.9966888160195643], [39, 0.993

In [20]:
file = open('CAP_result.csv', 'w+', newline ='') 
  
# writing the data into the file 
with file:     
    write = csv.writer(file) 
    write.writerows(result) 

# Making the Confusion Matrix